[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.15.1"
  HUGO_VERSION = "0.54.0"

[context.deploy-preview]
  command = "yarn build-preview"

## For now, disable the website and redirect to the app
## TODO Remove when the website is done
[[redirects]]
from = "/*"
to = "https://app.kfet-insa.fr/:splat"
status = 301
force = true
