[[main]]
    weight = 1
    name = "Features"
    URL = "/features"

[[main]]
    weight = 1
    name = "Pricing"
    URL = "/pricing"

[[main]]
    weight = 2
    name = "Resources"
    hasChildren = true

    [[main]]
    parent = "Resources"
    name = "Blog"
    URL = "/blog"
    weight = 1

    [[main]]
    parent = "Resources"
    name = "Contact"
    URL = "/contact"
    weight = 3
